/**
 * Deno types are only available in Deno, so we use a triple-slash directive to reference a separate
 * declaration file that provides the necessary types. This allows us to keep the Deno-specific types
 * isolated and avoid issues when running in other environments.
 *
 * The `deno.d.ts` file is generated by running `pnpm run gen:deno-types` (see
 * `scripts/gen-deno-types.mjs`), which ensures that we have up-to-date type definitions for the
 * Deno runtime without having to manually maintain them. Use the script rather than piping
 * `deno types` directly: PowerShell's redirect writes a BOM that breaks esbuild on Windows.
 */
/// <reference path="./ref/deno.d.ts" />

import type { LoggerTransportClass } from "../../../logger/types.js";
import type { SingletonExtension } from "../../extensions/singleton.js";
import type { HostRuntimeAdapter } from "../../types/adapter.js";
import { Logger } from "../../../logger/logger.js";
import { ConsoleTransport } from "../../../logger/transports/console.js";
import { singletonExtension } from "../../extensions/singleton.js";

/**
 * Placeholder Deno runtime adapter. Reads `flare.json` and exposes `Deno.env`, but
 * `createApp` and `createTestRequest` throw because the Deno runtime is not yet supported.
 */
export const deno: HostRuntimeAdapter<never, LoggerTransportClass, "async", SingletonExtension> = {
  runtime: "deno",
  lifecycle: "async",
  get flareJsonFile() {
    const filePath = `${Deno.cwd()}/flare.json`;
    return JSON.parse(Deno.readTextFileSync(filePath));
  },
  env: Deno.env.toObject(),
  defaultLoggerTransports: [ConsoleTransport],
  createApp() {
    throw new Error("Deno runtime is not yet supported");
  },
  createLogger(transports, container) {
    return new Logger(transports, container);
  },
  createTestRequest() {
    throw new Error("Deno runtime is not yet supported");
  },
  extendHost(host) {
    return singletonExtension(host);
  },
};
