/**
 * Helper functions called from inside the exec fns generated by exec-codegen.
 * Passed as `new Function()` parameters so V8 treats them as constants and
 * skips property-chain lookups per request.
 */

import type { JsonValue, SchemaToken } from "@flare-ts/lib/schema";
import type { HttpErrorContext } from "../../logger/types.js";
import type { Container } from "../../services/container.js";
import type { ErrorHandlerBase } from "./composition/classes/error-handler-base.js";
import type { FlareHttpContext } from "./transport/flare-http-context.js";
import type { ResponseLike } from "./transport/types/response.js";
import type { Pipeline } from "./types/pipeline.js";
import type { ErrorHandlerRegistration } from "./types/registration.js";
import { LOG_CONFIG } from "../../config/flare-config.js";
import { FlareError } from "../../errors/flare-error.js";
import { ErrorCategories } from "../../errors/types.js";
import { toErrorField } from "../../logger/fields.js";
import { Logger } from "../../logger/logger.js";
import { stream } from "./composition/contract/http-contract.js";
import { METHOD_IDX_MAP } from "./routing/types/methods.js";
import { SET_PARSED_BODY } from "./transport/flare-http-context.js";
import { ContentTooLarge } from "./transport/flare-request.js";
import { FlareResponse } from "./transport/flare-response.js";

/**
 * Buffers and validates the request body against the contract schema.
 * Returns void on success (sets parsed body on the http context),
 * or a ResponseLike short-circuit on validation failure or body-too-large.
 */
export function prepareRequestBody(
  ctx: FlareHttpContext,
  container: Container,
  pipeline: Pipeline,
): ResponseLike | void | Promise<ResponseLike | void> {
  const request = ctx.req;
  const methodIdx = METHOD_IDX_MAP[request.method as keyof typeof METHOD_IDX_MAP];
  if (methodIdx === undefined) return;

  const requestDescriptor = pipeline.flareRoute.requestDescriptors[methodIdx];
  const bodyDescriptor = requestDescriptor?.body;
  if (bodyDescriptor === undefined || bodyDescriptor === stream) return;

  const logger = container.resolveDep(Logger);
  // The stream sentinel was excluded by the caller's === stream check, which the
  // type system cannot connect to this union narrowing.
  const bodyContract = bodyDescriptor as SchemaToken<JsonValue>;

  return request
    .buffer()
    .then((buffer: ArrayBuffer | null): ResponseLike | void => {
      if (buffer === null) {
        ctx[SET_PARSED_BODY](null);
        return;
      }

      const parsedBody = bodyContract.safeParse(buffer);
      if (parsedBody.success) {
        ctx[SET_PARSED_BODY](parsedBody.data);
        return;
      }

      logger.warn("Request body validation failed", {
        details: parsedBody.error.fields,
      });

      return new FlareResponse(400, {
        error: "Invalid request body",
        details: parsedBody.error.fields,
      });
    })
    .catch((err: unknown): ResponseLike => {
      logger.warn("Request body parsing failed", { error: toErrorField(err) });

      if (err instanceof FlareError && err.name === ContentTooLarge.name) {
        return new FlareResponse(ErrorCategories[ContentTooLarge.category], {
          error: ContentTooLarge.name,
          code: ContentTooLarge.code,
          detail: err.detail as JsonValue,
        });
      }

      return new FlareResponse(400, { error: "Invalid request body" });
    });
}

/**
 * Try each registered error handler in order. Returns the first non-void ResponseLike,
 * or falls back to the default handleControllerError response.
 *
 * Each handler invocation is wrapped in its own try-catch so a throwing handler
 * never propagates out of this function: it logs and falls through to the next handler.
 * This prevents the pipeline's outer try-catches from re-entering dispatch and cascading.
 *
 * Reaching the fallback means no handler produced a response: handleControllerError logs the error
 * before the synthesized envelope replaces it (unless `log.unhandledErrors` is off).
 */
export function dispatchErrorHandlers(
  err: FlareError | Error,
  handlers: readonly ErrorHandlerRegistration[],
  container: Container,
  context: HttpErrorContext,
): ResponseLike | Promise<ResponseLike> {
  const logger = container.resolveDep(Logger);
  const logCfg = container.resolveCfg(LOG_CONFIG);

  function tryNext(idx: number): ResponseLike | Promise<ResponseLike> {
    if (idx >= handlers.length) {
      return handleControllerError(err, logger, logCfg.unhandledErrors, context);
    }

    let handler: ErrorHandlerBase;
    try {
      handler = handlers[idx]!.factory(container);
    } catch (err) {
      logger.error(err, "Error handler factory threw", _errorContextMeta(context));
      return tryNext(idx + 1);
    }

    let result: ReturnType<typeof handler.handle>;
    try {
      result = handler.handle(err, context);
    } catch (err) {
      logger.error(err, "Error handler handle() threw", _errorContextMeta(context));
      return tryNext(idx + 1);
    }

    if (_isPromise(result)) {
      return (result as Promise<ResponseLike | void>).then(
        (resolved) => {
          if (resolved && _isResponseLike(resolved)) return resolved;
          return tryNext(idx + 1);
        },
        (err) => {
          logger.error(err, "Error handler handle() rejected", _errorContextMeta(context));
          return tryNext(idx + 1);
        },
      );
    }
    if (result && _isResponseLike(result)) return result as ResponseLike;
    return tryNext(idx + 1);
  }

  return tryNext(0);
}

export function handleControllerError(
  err: FlareError | Error,
  logger: Logger,
  unhandledErrors: boolean,
  context: HttpErrorContext,
): ResponseLike {
  if (unhandledErrors !== false) {
    logger.error(err, "Unhandled error", _errorContextMeta(context));
  }

  if (err instanceof FlareError) {
    const detail = err.detail;
    const body: Record<string, JsonValue> = { error: err.name };
    if (err.code !== undefined) body.code = err.code;
    if (detail !== undefined) body.detail = detail;
    return new FlareResponse(ErrorCategories[err.category], body);
  }

  return new FlareResponse(500, { error: "Internal Server Error" });
}

function _isPromise<T>(value: T | Promise<T>): value is Promise<T> {
  return value instanceof Promise;
}

function _errorContextMeta(context: HttpErrorContext): Record<string, JsonValue> {
  const meta: Record<string, JsonValue> = { stage: context.stage ?? "unknown" };
  if (context.target) meta.target = context.target;
  return meta;
}

function _isResponseLike(value: unknown): value is ResponseLike {
  return value instanceof FlareResponse || value instanceof Response;
}
