/**
 * The extendable face of a schema: `model()` wraps a schema token in an abstract class
 * so DTOs can be named by extension, and owns the compiled-serializer static seam.
 */
import {
  type BranchShape,
  type DescriptorValue,
  type DiscriminantValues,
  type JsonValue,
  type SafeParseResult,
  SCHEMA_BRAND,
  SCHEMA_DESCRIPTOR,
  SCHEMA_REQUIRED,
  schema,
  type SchemaToken,
} from "./schema.js";
import { compileSerializer, type SchemaSerializer } from "./serializer.js";

/**
 * Unique symbol stored as a static property on every class generated by {@link model}.
 *
 * Its value is the compiled JSON serializer produced lazily by
 * {@link compileSerializer}. Consumers outside the lib package (e.g. the core transport
 * layer) access this symbol via {@link Symbol.for} with the same well-known key rather
 * than importing this module directly.
 *
 * Well-known key: `"@flare-ts/schema/compiled-serializer"`
 *
 * @internal
 */
// `as never` is the only way to type a `unique symbol` from Symbol.for.
export const COMPILED_SERIALIZER: unique symbol = Symbol.for(
  "@flare-ts/schema/compiled-serializer",
) as never;

/**
 * Schema token that also acts as an abstract base class for DTO authoring.
 *
 * Returned by {@link model}. Extend it to declare a named model class:
 * ```ts
 * class UserModel extends model({ id: uuid, name: string }) {}
 * ```
 *
 * Instances are typed as `T`, so properties are accessible directly without
 * any unwrapping. Only model tokens carry a construct signature; {@link SchemaToken}
 * values from {@link schema} are intentionally not extendable.
 */
export type ModelTokenBuilder<T> = (abstract new(...args: never[]) => T) & SchemaToken<T>;

/**
 * Creates an extendable schema token for naming and authoring model classes.
 *
 * Three calling forms are supported:
 *
 * **From a descriptor** - define field shapes inline:
 * ```ts
 * class UserModel extends model({
 *   id: uuid,
 *   name: string,
 * }) {}
 * ```
 *
 * **From an existing schema** - promote a {@link schema} token to a model token:
 * ```ts
 * const UserSchema = schema({ id: uuid, name: string });
 * class UserModel extends model(UserSchema) {}
 * ```
 *
 * **Discriminated union** - branch on a string discriminant key (TypeScript cannot
 * `extends` a union; use a const base class and cast the union branch):
 * ```ts
 * const PetBase = model<Cat | Dog, "union">("kind", {
 *   cat: { lives: int },
 *   dog: { breed: str },
 * });
 * class PetModel extends (PetBase as ModelTokenBuilder<Cat | Dog>) {}
 * ```
 *
 * The returned token also satisfies {@link SchemaToken}`<T>`, so it can be used
 * as a nested field value inside other schema descriptors.
 */
export function model<T extends object>(schema: SchemaToken<T>): ModelTokenBuilder<T>;
export function model<T extends object>(descriptor: { [K in keyof T]: DescriptorValue<T[K]>; }): ModelTokenBuilder<T>;
export function model<T extends object, _ extends "union", K extends keyof T & string = keyof T & string>(
  discriminant: K,
  branches: {
    [V in DiscriminantValues<T, K>]: { [F in keyof BranchShape<T, K, V>]: DescriptorValue<BranchShape<T, K, V>[F]>; };
  },
): ModelTokenBuilder<T>;
export function model<T extends object>(
  descriptorOrDiscriminant: SchemaToken<T> | { [K in keyof T]: DescriptorValue<T[K]>; } | (keyof T & string),
  branches?: { [key: string]: { [field: string]: DescriptorValue<T[keyof T]>; }; },
): ModelTokenBuilder<T> {
  let token: SchemaToken<T>;
  if (typeof descriptorOrDiscriminant === "object" && SCHEMA_BRAND in (descriptorOrDiscriminant as object)) {
    token = descriptorOrDiscriminant as SchemaToken<T>;
  } else {
    // The implementation signature of schema() is not among its public overloads; this
    // local view lets model() forward either calling form to the single implementation.
    type SchemaImpl = (
      descriptorOrDiscriminant: { [K in keyof T]: DescriptorValue<T[K]>; } | (keyof T & string),
      branches?: { [key: string]: { [field: string]: DescriptorValue<T[keyof T]>; }; },
    ) => SchemaToken<T>;
    token = (schema as SchemaImpl)(
      descriptorOrDiscriminant as { [K in keyof T]: DescriptorValue<T[K]>; } | (keyof T & string),
      branches,
    );
  }

  // The descriptor store is the declared SCHEMA_DESCRIPTOR erasure seam; the symbol
  // read needs an indexable view of the token.
  const tokenDescriptor = (token as Record<symbol, unknown>)[SCHEMA_DESCRIPTOR];
  let cachedSerializer: SchemaSerializer | undefined;
  const ModelClass = class {
    static readonly [SCHEMA_BRAND] = true;
    static [SCHEMA_REQUIRED] = true;
    static readonly [SCHEMA_DESCRIPTOR] = tokenDescriptor;
    static get [COMPILED_SERIALIZER](): SchemaSerializer {
      if (cachedSerializer === undefined) cachedSerializer = compileSerializer(token);
      return cachedSerializer;
    }
    static safeParse(raw: ArrayBuffer | string | JsonValue): SafeParseResult<T> {
      return token.safeParse(raw);
    }
    static optional(): SchemaToken<T> {
      return token.optional();
    }
  };

  return asModelToken<T>(ModelClass);
}

function asModelToken<T>(token: object): ModelTokenBuilder<T> {
  // The class expression carries the brand, descriptor, and parse statics by
  // construction; the checker cannot see them through the anonymous class type.
  return token as ModelTokenBuilder<T>;
}
