/**
 * The extendable face of a schema: `model()` wraps a schema token in an abstract class
 * so DTOs can be named by extension, and owns the compiled-serializer static seam.
 */
import {
  type DescriptorValue,
  type JsonValue,
  type SafeParseResult,
  SCHEMA_BRAND,
  SCHEMA_DESCRIPTOR,
  SCHEMA_REQUIRED,
  schema,
  type SchemaToken,
} from "./schema.js";
import { compileSerializer, type SchemaSerializer } from "./serializer.js";

/**
 * Unique symbol stored as a static property on every class generated by {@link model}.
 *
 * Its value is the compiled JSON serializer produced lazily by
 * {@link compileSerializer}. Consumers outside the lib package (e.g. the core transport
 * layer) access this symbol via {@link Symbol.for} with the same well-known key rather
 * than importing this module directly.
 *
 * Well-known key: `"@flare-ts/schema/compiled-serializer"`
 *
 * @internal
 */
// `as never` is the only way to type a `unique symbol` from Symbol.for.
export const COMPILED_SERIALIZER: unique symbol = Symbol.for(
  "@flare-ts/schema/compiled-serializer",
) as never;

/**
 * Schema token that also acts as an abstract base class for DTO authoring.
 *
 * Returned by {@link model}. Extend it to declare a named model class:
 * ```ts
 * class UserModel extends model({ id: uuid, name: string }) {}
 * ```
 *
 * Instances are typed as `T`, so properties are accessible directly without
 * any unwrapping. Only model tokens carry a construct signature; {@link SchemaToken}
 * values from {@link schema} are intentionally not extendable.
 */
export type ModelTokenBuilder<T> = (abstract new(...args: never[]) => T) & SchemaToken<T>;

/** Function-parameter contravariance collapses a union into an intersection. */
type UnionToIntersection<U> = (U extends unknown ? (x: U) => void : never) extends (x: infer I) => void ? I
  : never;

/**
 * Rejects union-typed schema tokens at the `model()` call site: a class cannot carry a
 * union instance type, so a union has no extendable face. Resolves to `unknown` (no
 * added constraint) for object shapes and to an error-message literal for unions.
 */
type NonUnionGuard<T> = [T] extends [UnionToIntersection<T>] ? unknown
  : "model() cannot wrap a union schema: a class cannot carry a union instance type. Use the schema token directly.";

/**
 * Creates an extendable schema token for naming and authoring model classes.
 *
 * Two calling forms are supported:
 *
 * **From a descriptor** - define field shapes inline:
 * ```ts
 * class UserModel extends model({
 *   id: uuid,
 *   name: string,
 * }) {}
 * ```
 *
 * **From an existing schema** - promote a {@link schema} token to a model token:
 * ```ts
 * const UserSchema = schema({ id: uuid, name: string });
 * class UserModel extends model(UserSchema) {}
 * ```
 *
 * Discriminated unions have no model form: a class cannot carry a union instance type,
 * so the extendable face `model()` exists for is unavailable to them. Use
 * `schema<T, "union">(discriminant, branches)` directly; a union-typed schema token is
 * rejected at the `model()` call site.
 *
 * The returned token also satisfies {@link SchemaToken}`<T>`, so it can be used
 * as a nested field value inside other schema descriptors.
 */
export function model<T extends object>(schema: SchemaToken<T> & NonUnionGuard<T>): ModelTokenBuilder<T>;
export function model<T extends object>(descriptor: { [K in keyof T]: DescriptorValue<T[K]>; }): ModelTokenBuilder<T>;
export function model<T extends object>(
  tokenOrDescriptor: SchemaToken<T> | { [K in keyof T]: DescriptorValue<T[K]>; },
): ModelTokenBuilder<T> {
  let token: SchemaToken<T>;
  if (SCHEMA_BRAND in (tokenOrDescriptor as object)) {
    token = tokenOrDescriptor as SchemaToken<T>;
  } else {
    // The descriptor overload of schema() infers its own shape; this local view lets
    // model() forward the already-constrained descriptor to the single implementation.
    type SchemaImpl = (descriptor: { [K in keyof T]: DescriptorValue<T[K]>; }) => SchemaToken<T>;
    token = (schema as SchemaImpl)(tokenOrDescriptor as { [K in keyof T]: DescriptorValue<T[K]>; });
  }

  // The descriptor store is the declared SCHEMA_DESCRIPTOR erasure seam; the symbol
  // read needs an indexable view of the token.
  const tokenDescriptor = (token as Record<symbol, unknown>)[SCHEMA_DESCRIPTOR];
  let cachedSerializer: SchemaSerializer | undefined;
  const ModelClass = class {
    static readonly [SCHEMA_BRAND] = true;
    static [SCHEMA_REQUIRED] = true;
    static readonly [SCHEMA_DESCRIPTOR] = tokenDescriptor;
    static get [COMPILED_SERIALIZER](): SchemaSerializer {
      if (cachedSerializer === undefined) cachedSerializer = compileSerializer(token);
      return cachedSerializer;
    }
    static safeParse(raw: ArrayBuffer | string | JsonValue): SafeParseResult<T> {
      return token.safeParse(raw);
    }
    static optional(): SchemaToken<T> {
      return token.optional();
    }
  };

  return asModelToken<T>(ModelClass);
}

function asModelToken<T>(token: object): ModelTokenBuilder<T> {
  // The class expression carries the brand, descriptor, and parse statics by
  // construction; the checker cannot see them through the anonymous class type.
  return token as ModelTokenBuilder<T>;
}
