/**
 * @internal
 *
 * Unique symbol stored as a static property on every class generated by
 * {@link model}. Its value is the compiled JSON serializer produced eagerly
 * at class-declaration time by {@link compileSerializer}.
 *
 * Consumers outside the lib package (e.g. the core transport layer) must
 * access this symbol via {@link Symbol.for} with the same well-known key
 * rather than importing this module directly.
 *
 * Well-known key: `"@flare-ts/schema/compiled-serializer"`
 */
export const COMPILED_SERIALIZER: unique symbol = Symbol.for(
  "@flare-ts/schema/compiled-serializer",
) as never;
