/**
 * Pins the live Node runtime's log-context wraps over a loopback socket: the
 * per-request HttpLogContext wrap around handler dispatch, and the HostLogContext
 * wrap around startup lifecycle emits. FLARE_MODE is left unset in the adapter env
 * so `host.build()` returns the real FlareAppNode.
 */
process.env["FLARE_MODE"] = "test";

import type { AddressInfo } from "node:net";
import { once } from "node:events";
import { describe, expect, it } from "vitest";
import type { JsonObject } from "@flare-ts/lib";
import type { HttpLogContext } from "../../../../../src/lib/logger/types.js";
import { FlareHost, FlareResponse, LoggerTransport, type LogRecord } from "../../../../../src/index.js";
import { node } from "../../../../../src/node.js";
import { type NodeTestAdapter } from "../../../../node/helpers/node-adapter.js";
import { registerMinimalPingRoute } from "../../../../portable/helpers/host-fixtures.js";

/** Builds a live Node adapter with empty `env` so `host.build()` returns FlareAppNode for runtime ALS tests. */
function nodeLiveAdapter(
  flareJson: JsonObject,
): NodeTestAdapter {
  return {
    runtime: node.runtime,
    lifecycle: node.lifecycle,
    env: {},
    defaultLoggerTransports: [],
    createApp: node.createApp.bind(node),
    createLogger: node.createLogger.bind(node),
    createTestRequest: node.createTestRequest.bind(node),
    extendHost: node.extendHost!.bind(node),
    get flareJsonFile(): JsonObject {
      return flareJson;
    },
  };
}

function newTestHost(adapter: NodeTestAdapter) {
  const host = new FlareHost(adapter);
  registerMinimalPingRoute(host);
  return host;
}

describe("Primary Behavior", () => {
  it("HTTP request scope (Node runtime): the per-request log-context wrap sets an HttpLogContext so every record emitted inside the handler carries it", async () => {
    // The Node runtime wraps each incoming request in `runWithLogStore` with an
    // HttpLogContext before dispatching to the HTTP arc. Use the live Node
    // runtime (not the test-mode shim) so we exercise that wrap end-to-end.
    const records: LogRecord[] = [];
    class CapturingTransport extends LoggerTransport {
      static override readonly transportName = "capture-http";
      static override deps: never[] = [];
      write(record: LogRecord): void {
        records.push(record);
      }
    }

    const host = newTestHost(nodeLiveAdapter({
      host: { port: 0, host: "127.0.0.1", requestIdHeader: true },
      log: { level: "trace", enableContext: true, format: "json" },
    }));
    host.logging.transport(CapturingTransport);

    // Handler logs from inside the request scope. The runtime's log-context
    // wrap must propagate the HttpLogContext to this emit.
    host.http.get("/log-here", () => {
      host.logger.info("handler-emit");
      return new FlareResponse(200, { ok: true });
    });

    const app = host.build();
    const handle = app.run();
    try {
      if (!handle.server.listening) {
        await once(handle.server, "listening");
      }
      const addr = handle.server.address() as AddressInfo;
      const res = await fetch(`http://127.0.0.1:${addr.port}/log-here`);
      expect(res.status).toBe(200);

      const rec = records.find((r) => r.message === "handler-emit");
      expect(rec).toBeDefined();
      // The HTTP arc subsystem's per-request scope produced an HttpLogContext.
      expect(rec!.context).toBeDefined();
      expect(rec!.context).toMatchObject({
        source: "flare:http",
        method: "GET",
        url: "/log-here",
      });
      // requestId is generated by the runtime; it must be a non-empty string.
      expect(typeof (rec!.context as HttpLogContext).requestId).toBe("string");
      expect((rec!.context as HttpLogContext).requestId.length).toBeGreaterThan(0);
    } finally {
      await handle.stop();
    }
  });

  it("host lifecycle code (Node runtime startup) emits records inside a HostLogContext so lifecycle traces are tagged with source: flare:host", async () => {
    // The Node runtime wraps `#start` in `runWithLogStore({ context:
    // { source: "flare:host" } })` when enableContext is on. The
    // "HTTP server started listening on ..." info log is emitted from inside
    // that scope and must carry the HostLogContext on the record.
    const records: LogRecord[] = [];
    class CapturingHostTransport extends LoggerTransport {
      static override readonly transportName = "capture-host";
      static override deps: never[] = [];
      write(record: LogRecord): void {
        records.push(record);
      }
    }

    const host = newTestHost(nodeLiveAdapter({
      host: { port: 0, host: "127.0.0.1" },
      log: { level: "trace", enableContext: true, format: "json" },
    }));
    host.logging.transport(CapturingHostTransport);

    const app = host.build();
    const handle = app.run();
    try {
      if (!handle.server.listening) {
        await once(handle.server, "listening");
      }

      // The "listening" info log fires once startup completes. Find it.
      const listening = records.find((r) => r.message.startsWith("HTTP server started listening"));
      expect(listening).toBeDefined();
      // It was emitted from inside the host lifecycle ALS scope.
      expect(listening!.context).toEqual({ source: "flare:host" });
    } finally {
      await handle.stop();
    }
  });
});
